### ISSUE TITLE
"vagrant up" failing after "vagrant halt"

### ISSUE THREAD

**Issue by anderssh** [rdbreak/rhce7env#2]
When using `vagrant halt` to stop my virtual machines, I get errors when using `vagrant up` to start my environment again. Using Virtualbox 6.0.16 and Vagrant 2.2.7 on Mac
```
A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "b5b58256-06a7-4842-af58-fe40c00ebeb7", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.
```

**Comment by rdbreak** [comment]
According to the vagrant documentation, this is by design: https://www.vagrantup.com/docs/cli/halt.html.

If you're want to shut down the VMs but use them later on, I suggest using `vagrant suspend` and `vagrant resume` to stop and start the VMs back up, respectively. 

Otherwise, when using the halt command, you'll need to manually boot up the VMs from virtualbox GUI.

**Comment by rdbreak** [comment]
I figured out a way to get this working. 

The newest push should fix this.

Thanks!
